language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang

install:
# Download conan
- wget http://downloads.conan.io/latest_debian -O conan.deb
- sudo dpkg -i conan.deb
- rm conan.deb

# Automatic detection of your arch, compiler, etc
- conan install

# Download conan
#- pip install conan
- conan remote add lms http://mineforce.de:9300


script:
- mkdir build
- cd build
- conan install .. --build=missing
- cmake .. -DBUILD_TESTS=ON -DCOVERAGE=ON && make
- bin/lmstest
after_success:
- bash <(curl -s https://codecov.io/bash)
