language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang

script:
- mkdir build
- cd build
- cmake .. -DBUILD_TESTS=ON -DCOVERAGE=ON && make
- test/lmstest
after_success:
- bash <(curl -s https://codecov.io/bash)
